# action.yml
name: 'PR-Pilot Briefing'
description: 'Analyzes a pull request diff and posts a summary briefing as a comment.'
author: 'Your Name'

inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'radio'
  color: 'blue'
